FROM python:3.11.6
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
WORKDIR /workdir/src/api
EXPOSE 8000
CMD ["uvicorn", "main:app", "--reload", "127.0.0.1", "--port", "8000"]